import sharp from "sharp";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import s3Client from "./s3Client.js";
import config from "../config/config.js";
import { loadImage, createCanvas } from "@napi-rs/canvas";
import fetch from "node-fetch";

async function fetchImageBuffer(urlOrPath) {
    if (urlOrPath.startsWith(config.CLOUDFRONT_BASE_URL)) {
        const key = urlOrPath.replace(config.CLOUDFRONT_BASE_URL + "/", "");
        const response = await s3Client.send(
            new GetObjectCommand({
                Bucket: config.AWS_S3_BUCKET_NAME,
                Key: key,
            })
        );
        const byteArray = await response.Body.transformToByteArray();
        return Buffer.from(byteArray);
    }

    const res = await fetch(urlOrPath);
    const ab = await res.arrayBuffer();
    return Buffer.from(ab);
}

/**
 * Overlays a logo onto a base64 background image
 * @param {string} base64Background - The image generated by Imagen 4
 * @param {string} logoPath - The URL or local path of the logo
 * @param {string} [position="top-right"] - Target position ("top-left", "top-right", "bottom-left", "bottom-right", "top-center", "bottom-center")
 * @param {object} [coords=null] - Optional normalized coordinates { x, y } (0-1)
 * @returns {Promise<string>} - The composited image in base64
 */
export async function compositeLogoOnFirstFrame(base64Background, logoPath, position = "top-right", coords = null) {
    try {
        // 1. Convert base64 background to Buffer for Sharp
        const backgroundBuffer = Buffer.from(base64Background, "base64");

        // 2. Fetch and prepare the Logo
        let logoBuffer = await fetchImageBuffer(logoPath);

        // Check if the logo is an SVG
        const isSvg = logoPath.toLowerCase().includes(".svg") || 
                      logoBuffer.slice(0, 100).toString("utf-8").trim().startsWith("<svg") ||
                      logoBuffer.slice(0, 100).toString("utf-8").trim().startsWith("<?xml");

        if (isSvg) {
            console.log("[imageCompositor] Logo is SVG, rendering to PNG using @napi-rs/canvas...");
            const img = await loadImage(logoBuffer);
            const canvas = createCanvas(img.width, img.height);
            const ctx = canvas.getContext("2d");
            ctx.drawImage(img, 0, 0);
            logoBuffer = await canvas.encode("png");
        }

        // Resize the logo Buffer (keeping it at ~350px wide for consistency)
        const resizedLogoBuffer = await sharp(logoBuffer)
            .resize({ width: 350, fit: "inside" })
            .toBuffer();

        // --- 3. DIMENSION & DYNAMIC POSITION CALCULATIONS ---
        const background = sharp(backgroundBuffer);
        const bgMetadata = await background.metadata();
        const logoMetadata = await sharp(resizedLogoBuffer).metadata();

        const padding = 30;
        let positionTop = padding;
        let positionLeft = bgMetadata.width - logoMetadata.width - padding;

        if (coords && typeof coords.x === 'number' && typeof coords.y === 'number') {
            positionLeft = Math.max(0, Math.min(bgMetadata.width - logoMetadata.width, Math.round(coords.x * bgMetadata.width)));
            positionTop = Math.max(0, Math.min(bgMetadata.height - logoMetadata.height, Math.round(coords.y * bgMetadata.height)));
        } else {
            const pos = String(position || 'top-right').toLowerCase().trim();
            if (pos === 'top-left') {
                positionTop = padding;
                positionLeft = padding;
            } else if (pos === 'bottom-left') {
                positionTop = bgMetadata.height - logoMetadata.height - padding;
                positionLeft = padding;
            } else if (pos === 'bottom-right') {
                positionTop = bgMetadata.height - logoMetadata.height - padding;
                positionLeft = bgMetadata.width - logoMetadata.width - padding;
            } else if (pos === 'top-center' || pos === 'top-middle') {
                positionTop = padding;
                positionLeft = Math.round((bgMetadata.width - logoMetadata.width) / 2);
            } else if (pos === 'bottom-center' || pos === 'bottom-middle') {
                positionTop = bgMetadata.height - logoMetadata.height - padding;
                positionLeft = Math.round((bgMetadata.width - logoMetadata.width) / 2);
            } else {
                // Default: top-right
                positionTop = padding;
                positionLeft = bgMetadata.width - logoMetadata.width - padding;
            }
        }

        // 4. Composite the images using calculated offsets
        const finalImageBuffer = await background
            .composite([
                {
                    input: resizedLogoBuffer,
                    top: positionTop,    // Apply calculated Y-axis
                    left: positionLeft,  // Apply calculated X-axis
                    blend: "over"
                }
            ])
            .toFormat("png")
            .toBuffer();

        // 5. Return the new base64 string
        return finalImageBuffer.toString("base64");
    } catch (error) {
        console.error("Error compositing logo:", error);
        throw error;
    }
}